version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
    
        ports:
            - "27017:27017"
        volumes:
            - dbvolume:/data/db

    fastify:
        build: .
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - mongodb
        environment:
            - MONGO_URL=mongodb://mongodb:27017/tasks
            - PORT=3000

volumes:
    dbvolume: